### ISSUE TITLE
Plugin disabling with error

### ISSUE THREAD

**Issue by GrandpaBlackTF2** [APDevTeam/Movecraft-Combat#101]
Anyone have any clue how to fix this problem?

[03:13:15] [Server thread/ERROR]: Error occurred while enabling Movecraft-Combat v2.0.0-a.6 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.THIN_GLASS
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at org.bukkit.Material.valueOf(Material.java:106) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.countercraft.movecraft.util.Tags.parseMaterials(Tags.java:131) ~[Movecraft(20).jar:?]
	at net.countercraft.movecraft.combat.features.directors.Directors.load(Directors.java:49) ~[Movecraft-Combat-2.0.0-a.6(1).jar:?]
	at net.countercraft.movecraft.combat.MovecraftCombat.onEnable(MovecraftCombat.java:73) ~[Movecraft-Combat-2.0.0-a.6(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TheSidOffical** [comment]
I think it couldnt find item named: thin_glass

Make sure item/block names are valid.

**Comment by TheSidOffical** [comment]
check here for vaild item/block names.

https://papermc.io/javadocs/paper/1.18/org/bukkit/Material.html

**Comment by TylerS1066** [comment]
This is one of the *many* changes between the legacy 1.10.2-1.12.2 material IDs and the new material names.  Sid's link should help you figure out the correct material names, or you can look at the [current default config](https://github.com/APDevTeam/Movecraft-Combat/blob/main/src/main/resources/config.yml).
